name: folks
description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
